### ISSUE TITLE
Doesn't work in Safari OSX/iOS

### ISSUE THREAD

**Issue by polycode-nz** [FrDH/mmenu-light#11] opened 2019-06-29 05:27 UTC
With a download of todays code - the child `<ul>` elements overlay the page and elements underneath can't be clicked.

The same child `<ul>` appear in the same place in Chrome and FireFox but the problem doesn't happen in those browsers, can still click the elements underneath.

Example: https://waipalibraries.polycode.co.nz

**Comment by FrDH** [comment] 2019-06-29 19:18
thank you for reporting the issue, I'll see if I can get it fixed.

**Comment by FrDH** [comment] 2019-06-29 21:22
should be fixed now, could you give v2.0.1 a try?

**Comment by polycode-nz** [comment] 2019-06-29 21:56
Working perfectly on OSX and IOS now. Thanks for the quick fix!

**Comment by djvolk** [comment] 2019-07-01 10:22
On iPhone Safari and Chrome long list (which need to scroll) dont'show - only white space. If I use 

`.mm ul {
    bottom: unset;
}`

items in the list are shown, but scrolling breaks. If the elements of the list fit into the height of the screen - they are displayed correctly.
Example: https://luxxy.com/ru/   (now, im usind bottom: unset;)

**Comment by polycode-nz** [comment] 2019-07-01 21:09
I don't see that behaviour. I doubled up the nav links https://waipalibraries.polycode.co.nz and I see them all and can scroll the nav list.

The site underneath scrolls too which is annoying but I think I saw a setting for that.

**Comment by djvolk** [comment] 2019-07-01 21:53
I think error only on children lists. Screenshots from iPhone
![photo_2019-07-02_00-52-29](https://user-images.githubusercontent.com/1019816/60468937-d58d1880-9c63-11e9-9ede-1396c8736fed.jpg)
![photo_2019-07-02_00-52-32](https://user-images.githubusercontent.com/1019816/60468938-d58d1880-9c63-11e9-94cd-0c37f2a98c12.jpg)

**Comment by FrDH** [comment] 2019-07-01 22:23
This is such an odd ios safari issue, apparently the `<ul>` becomes somewhat of invisible when it needs to scroll overflowing content. Without the need for a scrollbar (either due to not enough listitems or to setting `overflow: hidden`), everything works as expected.

I'll have to dig deeper into why this occurs and how to work around it.

**Comment by FrDH** [comment] 2019-07-02 07:08
I don't know if this is by design or a bug, but ios safari does not show fixed elements outside of a parent with `overflow: hidden` (all other browsers do). Untill they change this behavior / fix this bug, I'l have to create a weird hacky workaround where the parent is actually 200% wide so the child is inside it.

**Comment by djvolk** [comment] 2019-07-02 10:37
Yes, its very strange bug. Chrome on iphone has the same problem. Waiting for a weird hacky workaround. The main thing is that there are no problems with the overlay, when the menu is closed.

**Comment by FrDH** [comment] 2019-07-02 21:29
could you give 2.0.2 a try?

**Comment by djvolk** [comment] 2019-07-03 12:48
Now everything is working correctly, thanks for fix!

**Comment by polycode-nz** [comment] 2019-07-03 23:20
Updated and is working on iPhone X Safari and Desktop. Thank you!

**Closed** 2019-07-05 06:25 UTC
Labels: bug

**Comment by xcartmods** [comment] 2020-05-01 10:55
Does anyone know what the specific CSS/JS changes were to fix the Safari issue?
