### ISSUE TITLE
Strange Bug width Chrome an opened submenus

### ISSUE THREAD

**Issue by rehm1967** [FrDH/mmenu-light#73] opened 2022-05-30 09:24 UTC
In the current Chrome browser there is a bug with the submenus when you navigate to a subcategory and then close and reopen the menu. The submenus are then no longer visible and are shifted to the left. Attached is a screenshot.
This can be reproduced with the current download
/demo/default.htm

![screen_bug](https://user-images.githubusercontent.com/106522585/170961298-36090051-2db0-4265-9d23-09084793f750.png)
l

**Comment by rehm1967** [comment] 2022-06-04 09:39
Does nobody have the same problem? Is there a way to fix this behavior?

**Comment by vever001** [comment] 2022-06-07 15:57
Thanks @gingapa !
It doesn't fix it completely (the borders before the chevrons are missing) but is is much better.

Note that this issue only seems to appear on an actual Android device with Chrome/Chromium  (I'm on version 102.0.5005.78).
I couldn't reproduce on desktop.

**Comment by rehm1967** [comment] 2022-06-07 16:29
thanks gingapa .. but your fix dosn't solve the problem. 

I commented out the following 2 "overflow" entries in the css file

`.mm-spn ul{
/*  overflow-y:auto; */

.mm-spn ul.mm-spn--parent{
/*  overflow-y:hidden; */
}`

So everything works as it should. I couldn't find any more display errors.

**Comment by gingapa** [comment] 2022-06-08 09:37
Dear @rehm1967 ,

your fix works really well but if we have submenu with many items we cannot scroll it vertically, that's an issue for us!

Thanks!

**Comment by rehm1967** [comment] 2022-06-08 10:54
you can actually undo all changes. the problem comes from this block here.

.mm-ocd__content {
    position: absolute;
    top: 0;
    bottom: 0;
    z-index: 2;
    width: var(--mm-ocd-width);
    min-width: var(--mm-ocd-min-width);
    max-width: var(--mm-ocd-max-width);
    background: #fff;
    **_-webkit-transition-property: -webkit-transform;
    transition-property: -webkit-transform;
    -o-transition-property: transform;
    transition-property: transform;
    transition-property: transform, -webkit-transform;
    -webkit-transition-duration: 0.3s;
    -o-transition-duration: 0.3s;
    transition-duration: 0.3s;
    -webkit-transition-timing-function: ease;
    -o-transition-timing-function: ease;
    transition-timing-function: ease;_**
}

If you remove the transitions everything works as desired. but that can't really be the solution.

**Comment by rehm1967** [comment] 2022-06-13 08:36
Here's a fix so that everything works as desired again:

Set all occurrences of 0s with 0.1s in the css file

So everything works as usual again. After that I couldn't find any more errors.

**Comment by gingapa** [comment] 2022-06-13 08:58
Thanks @rehm1967 still a workaround, but I don't see anything wrong going with it!

Cheers

**Comment by JackArbiter** [comment] 2022-06-24 20:45
Thanks @rehm1967, that worked flawlessly.

**Comment by chris-ard** [comment] 2022-07-05 13:03
@rehm1967 Thanks, can confirm that updating the transition delay appears to solve the issue.

**Comment by FrDH** [comment] 2022-09-12 21:27
Should be fixed n 3.2.0

**Closed** 2022-09-22 15:08 UTC
